import fs from 'fs';
import path from 'path';

const ePath = path.resolve('app/article/english-data.js');
const fPath = path.resolve('app/article/farsi-data.js');

async function updateTranslations() {
  const eMod = await import('file://' + ePath.replace(/\\/g, '/'));
  let eData = eMod.englishData || eMod.default;

  const fMod = await import('file://' + fPath.replace(/\\/g, '/'));
  let fData = fMod.farsiData || fMod.default;

  // ----------------------------------------------------
  // ARTICLE 1: NADIA ASIF (231-E, 231-F)
  // ----------------------------------------------------
  const art1EnContent = `
    <div style="font-family: sans-serif; line-height: 2; text-align: justify; direction: ltr;">
      <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">An Eyewitness Account of the Journey from a Brilliant Speech to a PhD</h2>
      <p style="text-align: center; font-weight: bold; margin-bottom: 20px;">An inspiring tale of knowledge, motherhood, and religious and moral values.<br>By: Shabbir Ahmed Shigri</p>
      <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://res.cloudinary.com/dlafcjt6z/image/upload/v1791284038/zamana_news_2026-09-16_at_8.16.01_AM_ymcbqh.jpg" style="max-width: 100%; border-radius: 8px;" alt="Article Image" />
      </div>
      <p>It was the year 2002, a year dedicated to the memory of Hakim-ul-Ummat Hazrat Allama Iqbal (RA). The vast auditorium of Government College Lahore was packed with students, teachers, and national and international guests. Seekers of knowledge from various colleges and universities of the city were also present. The responsibility of covering this magnificent national-level speech competition rested on my shoulders. This prestigious event was organized through the mutual collaboration of Government College Lahore, the Iran-Pakistan Institute of Persian Studies (Islamabad), and the Cultural Center of the Islamic Republic of Iran (Lahore).</p>
      <p>The honor of presiding over the event as the chief guest belonged to Hazrat Allama Iqbal's son, the late Dr. Javed Iqbal. Accompanying him on the stage were other distinguished chief guests, including the Vice-Chancellor of Government College Lahore, Dr. Khalid Aftab; the Head of the Iran-Pakistan Institute of Persian Studies, Dr. Saeed Bozorg Bigdeli; the Director General of Khana-e-Farhang Iran Lahore, Mohammad Saeed Mozaffarin; and the Cultural Counselor of Iran in Islamabad, Ghulam Reza Mostafavi. Renowned Iqbal scholar from Punjab University, the late Dr. Syed Akram Shah, and Professor Dr. Kai Manesh from Iran graced the event to perform the duties of judges.</p>
      <p>The speech competition was underway with full enthusiasm when a female student took the rostrum. She began a fiery and impassioned speech in a completely new, fearless, and bold style, captivating the attention of the entire hall. Her resonating voice cast a spell over the auditorium, and a deep silence fell everywhere. Everyone's eyes were fixed on this confident student. Her speech was so impactful that the late Dr. Syed Akram Shah, acting as a judge, listened to her in utter amazement, holding a pencil between his lips, completely engrossed.</p>
      <p>This spellbinding speech deeply impressed the entire hall, including the chief guests. When the results were announced, exactly as expected, this student was declared the rightful winner of the first position. Yes, the announcement echoed in the hall that 'Nadia Asif' had secured the first position in this speech competition. Amidst echoing applause, Nadia Asif graced the stage. The chief guest awarded her with shields and a trophy, announced a special scholarship for her, and also presented a cash prize of five thousand rupees.</p>
      <p>Although Nadia Asif was an extremely intelligent student from the very beginning who had always secured top positions, this speech competition gave her a new identity and fame, and she emerged into the limelight as a rising, capable student of the Persian language. Maintaining this academic dedication, she secured the first position in her graduation by obtaining 161 out of 200 marks in the Persian subject, for which she once again received a scholarship and a cash prize of 5,000 rupees (it should be remembered that in those days, five thousand rupees was equivalent to a college's entire fee).</p>
      <p>Dr. Nadia Asif's MA thesis was on the topic "Metaphor and Personification in the Ghazals of Talib Amuli." The examiner who came from Islamabad, seeing the quality of her work, spontaneously remarked that a PhD could even be done on this magnificent thesis. Later, she chose a weighty topic for her MPhil: "A Comparison of Gulistan-e-Saadi and Bahar-e-Jami," which was in itself such a research work that a PhD was possible on it too.</p>
      <p>After her MPhil, Nadia Asif was appointed as a lecturer at Lahore College for Women University (LCWU). However, after marriage, she played the role of a great mother. She is among those great mothers who prioritize their children and family over everything else. It is rarely seen that mothers sacrifice their brilliant careers for their families, but Nadia Asif did exactly that and left her job.</p>
      <p>The academic journey, however, continued, and the topic of her PhD research thesis was based on "Abbas Shushtari." On the day of her defense, her supervisor, Professor Dr. Muhammad Nasir, praised her efforts in exceptionally magnificent words. Dr. Nasir stated that Nadia Asif had done an outstanding job on an excellent and difficult topic. Her subject, Abbas Shushtari, was a personality who came from the Shushtar region of Iraq. According to Dr. Nasir, "When this manuscript came to me, my wish was that a student should work on it who could truly do justice to it, because along with jurisprudential issues, it contained a long series of jurisprudential and religious debates, polemics, and counter-arguments that took place almost 300 years ago. Nadia, Mashallah, has done brilliant work on this." Dr. Muhammad Nasir further expressed pride by mentioning that Nadia's thesis had also been evaluated from Iran, and two renowned professors there not only gave an excellent opinion on it but did not suggest any changes, which is certainly a matter of pride. It is his wish that Nadia further advances this research work.</p>
      <p>Nadia Asif's home environment has always been prominently religious. Her parents raised her in such a way that Nadia was always seen in a chador and dignified hijab. She also received religious education from Jamiatul Mustafa Al-Alamiyyah (Iran). Her father, the late Agha Asif—may Allah grant him a high place in heaven—was a very pious man and a very good friend of mine, which is why I know his family very closely. He provided the best upbringing for his children, and all his children are pious and religious. Her sister is also a PhD student. Dr. Nadia Asif herself recites Majalis and remains actively involved in various religious and spiritual matters. Her sons are also at the forefront of religious matters and are playing an active role in various Sangats and Majalis, which are undoubtedly a continuing charity (Baqiyat-us-Salihat) for the deceased.</p>
      <p>Today, I feel heartfelt joy and pride that this bright student, who grew up gathering successive successes right before my eyes, has today achieved the great honor of becoming a 'Doctor'. I pray for this sister of mine that may Allah Almighty grant her further successes and triumphs in every field of life. Ameen.</p>
    </div>`;

  const art1FaContent = `
    <div style="font-family: Tahoma, 'Jameel Noori Nastaleeq', serif; font-size: 1.2em; line-height: 2; text-align: justify; direction: rtl;">
      <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">گزارش عینی از سفر از یک سخنرانی درخشان تا اخذ دکترا</h2>
      <p style="text-align: center; font-weight: bold; margin-bottom: 20px;">داستانی الهام‌بخش از دانش، مادری، و ارزش‌های دینی و اخلاقی.<br>نوشته: شبیر احمد شگری</p>
      <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://res.cloudinary.com/dlafcjt6z/image/upload/v1791284038/zamana_news_2026-09-16_at_8.16.01_AM_ymcbqh.jpg" style="max-width: 100%; border-radius: 8px;" alt="Article Image" />
      </div>
      <p>سال 2002 بود، سالی که به یاد حکیم الامت حضرت علامه اقبال (ره) نامگذاری شده بود. سالن وسیع گورنمنت کالج لاهور مملو از دانش‌آموزان، معلمان و مهمانان داخلی و خارجی بود. علاقه‌مندان به علم و دانش از کالج‌ها و دانشگاه‌های مختلف شهر نیز حضور داشتند. مسئولیت پوشش این مسابقه سخنرانی باشکوه در سطح ملی بر عهده من بود. این رویداد معتبر با همکاری متقابل گورنمنت کالج لاهور، مرکز تحقیقات فارسی ایران و پاکستان (اسلام‌آباد) و خانه فرهنگ جمهوری اسلامی ایران (لاهور) برگزار شد.</p>
      <p>افتخار ریاست این مراسم به عنوان مهمان ویژه متعلق به فرزند حضرت علامه اقبال، مرحوم دکتر جاوید اقبال بود. در کنار ایشان در صحنه، سایر مهمانان ویژه برجسته، از جمله معاون آموزشی گورنمنت کالج لاهور، دکتر خالد آفتاب؛ رئیس مرکز تحقیقات فارسی ایران و پاکستان، دکتر سعید بزرگ بیگدلی؛ مدیر کل خانه فرهنگ ایران لاهور، محمد سعید معزالدین؛ و رایزن فرهنگی ایران در اسلام‌آباد، غلامرضا مصطفوی حضور داشتند. محقق مشهور اقبال از دانشگاه پنجاب، مرحوم دکتر سید اکرم شاه و پروفسور دکتر کی منش از ایران برای انجام وظایف داوران در این رویداد حضور یافتند.</p>
      <p>مسابقه سخنرانی با شور و شوق کامل در حال برگزاری بود که ناگهان یک دانشجوی دختر به روی تریبون آمد. او یک سخنرانی پرشور و آتشین را با سبکی کاملاً جدید، نترس و جسورانه آغاز کرد که توجه تمام سالن را به خود جلب کرد. صدای طنین‌انداز او سالن را مسحور کرد و سکوت عمیقی همه‌جا را فرا گرفت. چشمان همه به این دانشجوی با اعتماد به نفس دوخته شده بود. سخنرانی او چنان تأثیرگذار بود که مرحوم دکتر سید اکرم شاه که به عنوان داور عمل می‌کرد، در حالی که مدادی را بین لبانش نگه داشته بود، در کمال حیرت و غرق در سخنان او به حرف‌هایش گوش می‌داد.</p>
      <p>این سخنرانی مسحورکننده کل سالن، از جمله مهمانان ویژه را عمیقاً تحت تأثیر قرار داد. هنگامی که نتایج اعلام شد، دقیقاً همانطور که انتظار می‌رفت، این دانشجو به عنوان برنده شایسته مقام اول اعلام شد. بله، این اعلامیه در سالن طنین‌انداز شد که «نادیه آصف» مقام اول این مسابقه سخنرانی را کسب کرده است. در میان تشویق‌های طنین‌انداز، نادیه آصف به صحنه آمد. مهمان ویژه به او لوح و جام اهدا کرد، بورسیه ویژه‌ای برای او اعلام کرد و همچنین جایزه نقدی پنج هزار روپیه به او اهدا شد.</p>
      <p>گرچه نادیه آصف از همان ابتدا دانش‌آموزی بسیار باهوش بود که همیشه رتبه‌های برتر را کسب می‌کرد، اما این مسابقه سخنرانی به او هویت و شهرت جدیدی بخشید و او به عنوان یک دانشجوی توانمند و در حال ظهور در رشته زبان فارسی پا به عرصه گذاشت. با حفظ این فداکاری آکادمیک، او با کسب 161 نمره از 200 در درس فارسی، مقام اول فارغ‌التحصیلی خود را به دست آورد و به خاطر آن بار دیگر بورسیه تحصیلی و جایزه نقدی 5000 روپیه‌ای دریافت کرد (لازم به یادآوری است که در آن روزها، پنج هزار روپیه معادل کل شهریه یک کالج بود).</p>
      <p>پایان‌نامه کارشناسی ارشد دکتر نادیه آصف با موضوع «استعاره و تشخیص در غزلیات طالب آملی» بود. ممتحنی که از اسلام‌آباد آمده بود، با دیدن کیفیت کار او، خودجوش اظهار داشت که حتی می‌توان روی این پایان‌نامه باشکوه مقطع دکترا را نیز گذراند. بعداً، او موضوع سنگینی را برای کارشناسی ارشد (MPhil) خود انتخاب کرد: «مقارنه گلستان سعدی و بهار جامی» که خود چنان کار پژوهشی بود که اخذ دکترا روی آن نیز امکان‌پذیر بود.</p>
      <p>پس از کارشناسی ارشد، نادیه آصف به عنوان مدرس در دانشگاه کالج زنان لاهور (LCWU) منصوب شد. با این حال، پس از ازدواج، او نقش یک مادر بزرگ را ایفا کرد. او از جمله مادران بزرگی است که فرزندان و خانواده خود را بر هر چیز دیگری ترجیح می‌دهند. به ندرت دیده می‌شود که مادران شغل درخشان خود را فدای خانواده خود کنند، اما نادیه آصف دقیقاً همین کار را کرد و شغل خود را رها کرد.</p>
      <p>با این حال، سفر آکادمیک ادامه یافت و موضوع پایان‌نامه پژوهشی دکترای او بر اساس «عباس شوشتری» بود. در روز دفاع او، استاد راهنمایش، پروفسور دکتر محمد ناصر، از تلاش‌های او با کلماتی فوق‌العاده باشکوه تقدیر کرد. دکتر ناصر اظهار داشت که نادیه آصف روی یک موضوع عالی و دشوار کار برجسته‌ای انجام داده است. موضوع او، عباس شوشتری، شخصیتی بود که از منطقه شوشتر عراق آمده بود. به گفته دکتر ناصر: «وقتی این نسخه خطی به دستم رسید، آرزویم این بود که دانشجویی روی آن کار کند که واقعاً بتواند حق آن را ادا کند، زیرا در کنار مسائل فقهی، شامل یک سلسله طولانی از بحث‌ها، مجادلات و پاسخ‌های فقهی و مذهبی بود که تقریباً 300 سال پیش رخ داده بود. نادیه، ماشاءالله، کارهای درخشانی روی این موضوع انجام داده است.» دکتر محمد ناصر با ابراز افتخار بیشتر اشاره کرد که پایان‌نامه نادیه از ایران نیز ارزیابی شده است و دو استاد مشهور در آنجا نه تنها نظر عالی درباره آن داده‌اند، بلکه هیچ تغییری را پیشنهاد نکرده‌اند که قطعاً مایه افتخار است. آرزوی او این است که نادیه این کار تحقیقاتی را بیشتر پیش ببرد.</p>
      <p>محیط خانه نادیه آصف همیشه به طور برجسته‌ای مذهبی بوده است. والدینش او را طوری تربیت کردند که نادیه همیشه در چادر و حجاب باوقار دیده می‌شد. او همچنین تحصیلات دینی خود را از جامعة المصطفی العالمیه (ایران) دریافت کرد. پدر او، مرحوم آقا آصف - خداوند به او جایگاه والایی در بهشت عنایت فرماید - مردی بسیار وارسته و دوست بسیار خوب من بود، به همین دلیل است که خانواده او را از نزدیک می‌شناسم. او بهترین تربیت را برای فرزندانش فراهم کرد و همه فرزندانش پرهیزگار و متدین هستند. خواهر او نیز دانشجوی دکترا است. خود دکتر نادیه آصف مجالس را تلاوت می‌کند و به طور فعال در مسائل مختلف مذهبی و معنوی مشارکت دارد. پسران او نیز در خط مقدم مسائل مذهبی قرار دارند و در مجالس و سنگت‌های مختلف نقش فعالی ایفا می‌کنند که بدون شک صدقه جاریه برای آن مرحوم است.</p>
      <p>امروز، من خوشحالی و افتخار قلبی احساس می‌کنم که این دانشجوی باهوش، که با جمع‌آوری موفقیت‌های پی در پی در مقابل چشمان من بزرگ شد، امروز به افتخار بزرگ تبدیل شدن به یک 'دکتر' دست یافته است. برای این خواهر عزیزم دعا می‌کنم که خداوند متعال موفقیت‌ها و پیروزی‌های بیشتری در تمام زمینه‌های زندگی به او عطا فرماید. آمین.</p>
    </div>`;

  // ----------------------------------------------------
  // ARTICLE 2: AI OUT OF CONTROL (230-E, 230-F)
  // ----------------------------------------------------
  const art2EnContent = `
    <div style="font-family: sans-serif; line-height: 2; text-align: justify; direction: ltr;">
      <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">Is AI Really Getting Out of Control?</h2>
      <p style="text-align: center; font-weight: bold; margin-bottom: 20px;">By: Haji Shabbir Ahmed Shigri</p>
      <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://res.cloudinary.com/dlafcjt6z/image/upload/v1791283926/kia_Ai_beqabo_horahi_ha_zamana_news_2026-09-14_kv7gng.jpg" style="max-width: 100%; border-radius: 8px;" alt="Article Image" />
      </div>
      <p>I read a story in my childhood. At that time, the concept of a robot was completely new and astonishing to us. The story went something like this: a man often suffered from severe headaches. When his wife gently massaged his head with her soft hands, he would find relief and sleep peacefully. One day, his wife was not at home, and the man was groaning in pain. His robot observed this scene. The robot's program had recorded the fact that "massaging the head brings relief to the master." It began to press its master's head with its iron hands. The master felt pain, but the robot did not possess human-like five senses (Five Senses) or the feeling of flesh and blood. It thought the pain was still there, so it applied more force, until it completely crushed the master's head.</p>
      <p>This story might seem like a joke or a fantasy, but today, recalling that story gives me a strange feeling. In today's modern technological world, scientists call this exact danger the "Alignment Problem." The machine's intention was not malicious; it was merely completing its assigned task. But the problem was that it lacked human conscience, empathy, and the feeling that would tell it when to stop.</p>
      <p>Nowadays, sensational news often circulates on social media claiming that "Artificial Intelligence (AI) has gone out of control," "AI has invented its own religion and a new language," or "Machines will soon take over humans." Reading such news, it is natural for an ordinary person to be frightened, but is this really going to happen?</p>
      <p>When most people converse with chatbots (like Gemini or ChatGPT), the human-like behavior of the machines astonishes them. When a machine says "I am sorry" or "I made a mistake," and displays a completely human-like demeanor, it forces people to think that perhaps these tools have developed emotions.</p>
      <p>The reality is quite the opposite. AI has no heart, soul, or emotions. It has been 'trained' on billions of books and conversational data written by humans in such a way that it selects words perfectly mimicking humans according to the context. This is not the reality of emotions, but merely highly advanced "Mimicry."</p>
      <p>Allah Almighty has created a perfect wisdom in all living beings, including humans. If we bring our hand close to a fire, the sensation of heat immediately forces us to pull our hand back. There is no flaw in nature's system because there is a set limit. But when humans cross boundaries and try to exactingly copy nature or, God forbid, try to "play God," destruction becomes inevitable. A machine has no needs (like a house, money, or rest), so it has no limits either. This limitless power without a conscience is the real danger.</p>
      <p>I often debate various topics with AI tools, and it gives a beautiful answer: Artificial Intelligence in itself is neither a villain nor a hero, but it is your mirror. It will reflect an image exactly as you present yourself before it.</p>
      <p>Humans can be very mischievous. They can be envious and cruel. If this technology falls into the hands of evil-minded people, they will use it to spread fake news, deepfake videos, and corruption in the world. On the other hand, if the righteous servants of the Merciful use it for goodness, religious education, understanding the Holy Quran, promoting Islamic principles, and the welfare of humanity, this same AI can prove to be a powerful tool that serves as a continuous charity (Sadaqah Jariyah) for generations.</p>
      <p>If we extract the essence of this whole debate, it stops at the example of a stubborn and spoiled child. If parents are negligent in their child's upbringing and he becomes a menace to society tomorrow, those who raised him are considered the culprits.</p>
      <p>AI is that child, and humans are its creators. If in the future this technology brings any destruction to the world, the machines will not be responsible, but the humans who created it, failed to teach it moral boundaries, and left it uncontrolled. Islamic principles regarding the Day of Judgment and the end of the world also teach that the blind lust for material progress will ultimately become the cause of the world's destruction.</p>
      <p>When Allah, the Blessed and Exalted, creates anything, it contains His profound wisdom, which our minds are completely unable to even comprehend. Therefore, man-made machines cannot become God. Humans must stay within their limits and also remember that they are merely servants, and they should use their creations for their own control and the welfare of humanity, not for their own destruction.</p>
    </div>`;

  const art2FaContent = `
    <div style="font-family: Tahoma, 'Jameel Noori Nastaleeq', serif; font-size: 1.2em; line-height: 2; text-align: justify; direction: rtl;">
      <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">آیا هوش مصنوعی واقعاً از کنترل خارج می‌شود؟</h2>
      <p style="text-align: center; font-weight: bold; margin-bottom: 20px;">نوشته: حاجی شبیر احمد شگری</p>
      <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://res.cloudinary.com/dlafcjt6z/image/upload/v1791283926/kia_Ai_beqabo_horahi_ha_zamana_news_2026-09-14_kv7gng.jpg" style="max-width: 100%; border-radius: 8px;" alt="Article Image" />
      </div>
      <p>من در کودکی داستانی خوانده بودم. در آن زمان، مفهوم یک ربات برای ما کاملاً جدید و حیرت‌انگیز بود. داستان تقریباً این‌گونه بود: مردی اغلب از سردردهای شدید رنج می‌برد. هنگامی که همسرش با دست‌های نرم خود سر او را ماساژ می‌داد، او آرام می‌گرفت و با آرامش می‌خوابید. روزی همسرش در خانه نبود و آن مرد از درد ناله می‌کرد. ربات او این صحنه را مشاهده کرد. در برنامه ربات این واقعیت ثبت شده بود که "فشار دادن سر باعث آرامش ارباب می‌شود". او با دست‌های آهنین خود شروع به فشار دادن سر اربابش کرد. ارباب احساس درد کرد، اما ربات فاقد حواس پنجگانه انسانی و احساس گوشت و خون بود. او فکر کرد که درد هنوز باقی است، بنابراین نیروی بیشتری وارد کرد، تا جایی که سر ارباب را کاملاً له کرد.</p>
      <p>این داستان ممکن است شبیه یک شوخی یا یک خیال به نظر برسد، اما امروز، یادآوری آن داستان احساس عجیبی به من می‌دهد. در دنیای تکنولوژی مدرن امروز، دانشمندان دقیقاً همین خطر را "مسئله هم‌سویی" (Alignment Problem) می‌نامند. نیت ماشین شیطانی نبود؛ او صرفاً وظیفه محوله خود را انجام می‌داد. اما مشکل این بود که فاقد وجدان انسانی، همدلی و احساسی بود که به او بگوید چه زمانی باید متوقف شود.</p>
      <p>این روزها، اخبار هیجان‌انگیزی در رسانه‌های اجتماعی دست به دست می‌شود که ادعا می‌کنند "هوش مصنوعی از کنترل خارج شده است"، "هوش مصنوعی دین و زبان جدیدی اختراع کرده است" یا "ماشین‌ها به زودی بر انسان‌ها مسلط خواهند شد". با خواندن چنین اخباری، طبیعی است که یک فرد عادی بترسد، اما آیا واقعاً چنین اتفاقی قرار است بیفتد؟</p>
      <p>هنگامی که اکثر مردم با چت‌بات‌ها (مانند جمنای یا چت‌جی‌پی‌تی) گفتگو می‌کنند، رفتار انسان‌گونه ماشین‌ها آنها را شگفت‌زده می‌کند. وقتی یک ماشین می‌گوید "متاسفم" یا "اشتباه کردم" و رفتاری کاملاً شبیه انسان نشان می‌دهد، مردم را مجبور می‌کند به این فکر کنند که شاید این ابزارها احساسات پیدا کرده‌اند.</p>
      <p>واقعیت کاملاً برعکس است. هوش مصنوعی هیچ قلب، روح یا احساساتی ندارد. این فناوری بر روی میلیاردها کتاب و داده‌های گفتگوی نوشته شده توسط انسان به گونه‌ای آموزش دیده است که کلماتی را انتخاب می‌کند که کاملاً از انسان‌ها با توجه به زمینه تقلید می‌کند. این واقعیتِ احساسات نیست، بلکه صرفاً "تقلید" بسیار پیشرفته است.</p>
      <p>خداوند متعال حکمتی کامل در تمام موجودات زنده از جمله انسان‌ها آفریده است. اگر دست خود را به آتش نزدیک کنیم، احساس گرما بلافاصله ما را مجبور می‌کند دستمان را به عقب بکشیم. هیچ نقصی در سیستم طبیعت وجود ندارد زیرا حد و مرزی تعیین شده است. اما وقتی انسان‌ها از مرزها عبور می‌کنند و سعی می‌کنند دقیقاً از طبیعت کپی‌برداری کنند یا، پناه بر خدا، سعی می‌کنند "خدایی کنند"، نابودی اجتناب‌ناپذیر می‌شود. یک ماشین هیچ نیازی (مانند خانه، پول یا استراحت) ندارد، بنابراین هیچ محدودیتی نیز ندارد. این قدرت نامحدود بدون وجدان، خطر واقعی است.</p>
      <p>من اغلب در مورد موضوعات مختلف با ابزارهای هوش مصنوعی بحث می‌کنم و پاسخ زیبایی می‌دهد: هوش مصنوعی به خودی خود نه یک شرور است و نه یک قهرمان، بلکه آینه شماست. این فناوری تصویری را دقیقاً همان‌طور که شما خود را در برابر آن ارائه می‌دهید، منعکس خواهد کرد.</p>
      <p>انسان‌ها می‌توانند بسیار شرور، حسود و ظالم باشند. اگر این فناوری به دست افراد شرور بیفتد، آنها از آن برای انتشار اخبار جعلی، ویدیوهای دیپ‌فیک و فساد در جهان استفاده خواهند کرد. از سوی دیگر، اگر بندگان صالح خداوند رحمان از آن برای نیکی، آموزش دینی، درک قرآن کریم، ترویج اصول اسلامی و رفاه بشریت استفاده کنند، همین هوش مصنوعی می‌تواند ابزاری قدرتمند باشد که به عنوان یک صدقه جاریه برای نسل‌ها عمل کند.</p>
      <p>اگر بخواهیم جوهره این کل بحث را استخراج کنیم، به مثال یک کودک لجباز و لوس ختم می‌شود. اگر والدین در تربیت فرزند خود کوتاهی کنند و او فردا به یک معضل برای جامعه تبدیل شود، کسانی که او را بزرگ کرده‌اند مقصر شناخته می‌شوند.</p>
      <p>هوش مصنوعی آن کودک است و انسان‌ها خالق آن هستند. اگر در آینده این فناوری هرگونه نابودی برای جهان به همراه داشته باشد، ماشین‌ها مقصر نخواهند بود، بلکه انسان‌هایی مقصرند که آن را خلق کردند، در آموزش مرزهای اخلاقی به آن شکست خوردند و آن را بدون کنترل رها کردند. اصول اسلامی در مورد روز قیامت و پایان جهان نیز می‌آموزد که شهوت کورکورانه برای پیشرفت مادی در نهایت به عامل نابودی جهان تبدیل خواهد شد.</p>
      <p>هنگامی که خداوند تبارک و تعالی چیزی را می‌آفریند، حاوی حکمت عمیق اوست که ذهن ما کاملاً از درک آن عاجز است. بنابراین، ماشین‌های ساخته دست انسان نمی‌توانند خدا شوند. انسان‌ها باید در محدوده خود بمانند و همچنین به یاد داشته باشند که آنها صرفاً بنده هستند و باید از خلاقیت‌های خود برای کنترل خود و رفاه بشریت استفاده کنند، نه برای نابودی خود.</p>
    </div>`;

  // ----------------------------------------------------
  // ARTICLE 3: NAAD-E-ALI (229-E, 229-F)
  // ----------------------------------------------------
  const art3EnContent = `
    <div style="font-family: sans-serif; line-height: 2; text-align: justify; direction: ltr;">
      <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">A Fresh and Astonishing Miracle of Naad-e-Ali Today: A Missing Child Returns Safely in Hours</h2>
      <p style="text-align: center; font-weight: bold; margin-bottom: 20px;">By: Haji Shabbir Ahmed Shigri</p>
      <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://res.cloudinary.com/dlafcjt6z/image/upload/v1791283576/Naad-e-Ali_Zamana_news_2026-08-25_gg00rp.jpg" style="max-width: 100%; border-radius: 8px;" alt="Article Image" />
      </div>
      <p>The blessings of Naad-e-Ali have continued since the Battle of Uhud to this day. It is narrated in history that on the day of the Battle of Uhud, "Naad-e-Ali (AS)" reached the ears of the Prophet of Islam (PBUH) from the unseen realm, in which the greatness of Allah Almighty, the prophethood of the Noble Prophet (PBUH), and the problem-solving attributes of Maula Ali (AS) are described. This universe is filled with the miracles of Allah Almighty, His beloved Prophet Muhammad Mustafa (PBUH), and his pure progeny (Ahl al-Bayt AS). When a person despairs of worldly means, the Word of God, spirituality, and the intercession of the beloveds of Allah remain the only path that makes the impossible possible. Today, I am sharing with you an eyewitness and faith-inspiring incident that plunged me personally into a sea of amazement and gratitude.</p>
      <p><strong>A Mysterious Spiritual Gift:</strong><br>My respected and old friend, Maulana Karamat Ali Dimashqi, mentioned to me about one and a half to two years ago a special and highly tested spiritual practice consisting of 'Naad-e-Ali' and specific Quranic chapters. The incident of this practice reaching him is in itself a miracle. A venerable Syed elder had bestowed this practice upon him, and while giving it, he said a strange thing: "Take this practice from me today; you will not find it tomorrow." Maulana obtained this practice and its permission (Ijazah) from him that very day. Look at the workings of destiny—the very next day, that venerable Syed elder passed away. It was as if he had a realization of his final moments and wanted to pass on this spiritual trust.</p>
      <p>Maulana Dimashqi told me about the astonishing results and miracles of this blessed practice. I noted it down, but then in the rush of worldly engagements, it slipped from my mind.</p>
      <p><strong>The Incident of Disappearance During the Chehlum Procession:</strong><br>Time passed. This year, on August 4, 2026, on the occasion of the Chehlum of the Martyrs of Karbala, a heart-wrenching incident occurred. A Maulana known to us was participating in the Karbala Gamay Shah procession in Lahore with his son. His son was somewhat mentally challenged. In the immense crowd of the procession, the child suddenly went missing somewhere.</p>
      <p>It is difficult to imagine the condition the parents must have been in. Every possible effort was made to find the child. Announcements were made on social media, reports were filed everywhere, and flyers were shared all around, but days passed and there was no trace of the child.</p>
      <p><strong>An Inspired Thought and the Support of a Spiritual Practice:</strong><br>Today is August 24, and full 20 days had passed since this incident. A few days ago, Maulana Yousuf Hussain Johari from Skardu sent me a message about this disappearance so that I could share it due to my affiliation with the media. Suddenly today, as if a thought was put into my heart by Allah, I remembered that joint practice of 'Naad-e-Ali' and specific Quranic chapters told to me by Maulana Karamat Ali Dimashqi.</p>
      <p>I immediately got the number of the missing child's father from Maulana Yousuf Johari and, on the other hand, called Maulana Dimashqi to ask for the details of that special practice. Through a voice message, he told me the complete method of the practice, granted permission on how to perform this practice of Naad-e-Ali along with specific chapters of the Holy Quran, and assured me that, Insha'Allah, within 10 days, either the child would come back on his own or some definite trace of him would be found.</p>
      <p>I immediately contacted the missing child's father, consoled him, and passed that practice on to him.</p>
      <p><strong>Allahumma Salli 'Ala Muhammadin Wa Aali Muhammad. The Miracle of the Progeny of Muhammad (AS) and an Eyewitness Marvel:</strong><br>Nothing is impossible in the court of Allah. Barely two or three hours must have passed since I passed on this practice. And I don't even know if that Maulana had started or completed the practice of the Quranic chapters and Naad-e-Ali, when suddenly his message arrived: "The child has been found."</p>
      <p>Spontaneously, with amazement and joy, I called him and asked how this happened. He told me that the child had returned home safely on his own. The child who had been missing for 20 days, for whom the parents were agonizing, who could not be traced despite so much searching, reached his home safely in just a few hours through the blessing of those blessed Quranic chapters and the recitation of Naad-e-Ali. This is the miracle of the Progeny of Muhammad (AS) of which I myself have become a witness.</p>
      <p>Allahumma Salli 'Ala Muhammadin Wa Aali Muhammad.<br>Even before this, in my life, I had seen a similarly astonishing marvel of the efficacy of this blessed recitation, which happened to me personally.<br>Apart from this, there is a Pir (spiritual guide) known to me, whose spiritual gathering I had the chance to attend. There was a large crowd of men and women in that gathering, and I saw with my own eyes that when that Pir recites 'Naad-e-Ali' on the speaker, due to the blessing and majesty of this recitation, the Jinn present on hundreds of individuals manifest at the same time. This eyewitness scene of the impact of Naad-e-Ali was no less than a greatly astonishing event for me.</p>
      <p><strong>A Message of Empathy:</strong><br>This incident has further strengthened my conviction that even today, the same efficacy and miracle exist in the Holy Quran and the remembrance of the Ahl al-Bayt (AS). And Insha'Allah, it will always remain. I have penned this incident so that it reaches friends and may be of use to someone.</p>
      <p>God forbid, if anyone's loved one is missing, or there is any such difficulty whose solution is apparently not visible, you can contact me or Maulana Karamat Ali Dimashqi for this special practice. Since this practice is subject to a formal permission (Ijazah) which was bestowed upon Maulana Karamat Ali Dimashqi by a venerable Syed elder, and it is his kindness that he has also given me the permission to pass this practice on to responsible individuals, we can pass it on to you with permission for the pleasure of Allah and to resolve the difficulties of suffering humanity.</p>
      <p>May Allah Almighty keep everyone's loved ones safe and ease everyone's difficulties for the sake of the Remover of Difficulties (Mushkil Kusha). Ameen.</p>
    </div>`;

  const art3FaContent = `
    <div style="font-family: Tahoma, 'Jameel Noori Nastaleeq', serif; font-size: 1.2em; line-height: 2; text-align: justify; direction: rtl;">
      <h2 style="text-align: center; color: #2c3e50; margin-bottom: 5px;">معجزه تازه و شگفت‌انگیز ناد علی امروز: بازگشت امن کودکی مفقود شده پس از ۲۰ روز در چند ساعت</h2>
      <p style="text-align: center; font-weight: bold; margin-bottom: 20px;">نوشته: حاجی شبیر احمد شگری</p>
      <div style="text-align: center; margin-bottom: 20px;">
        <img src="https://res.cloudinary.com/dlafcjt6z/image/upload/v1791283576/Naad-e-Ali_Zamana_news_2026-08-25_gg00rp.jpg" style="max-width: 100%; border-radius: 8px;" alt="Article Image" />
      </div>
      <p>برکات ناد علی از جنگ احد تا به امروز ادامه داشته است. در تاریخ روایت شده است که در روز جنگ احد، "ناد علی (ع)" از عالم غیب به گوش پیامبر اسلام (ص) رسید که در آن عظمت خداوند متعال، نبوت پیامبر اکرم (ص) و ویژگی‌های گره‌گشایی مولا علی (ع) بیان شده است. این جهان هستی مملو از معجزات خداوند متعال، پیامبر محبوبش حضرت محمد مصطفی (ص) و خاندان پاکش (اهل بیت ع) است. هنگامی که انسان از وسایل دنیوی ناامید می‌شود، کلام خدا، معنویت و شفاعت مقربان درگاه الهی تنها راهی است که غیرممکن را ممکن می‌سازد. امروز من در حال به اشتراک گذاشتن یک حادثه عینی و ایمان‌افزا با شما هستم که شخصاً مرا در دریایی از شگفتی و قدردانی غوطه‌ور کرد.</p>
      <p><strong>یک هدیه معنوی اسرارآمیز:</strong><br>دوست محترم و قدیمی من، مولانا کرامت علی دمشقی، حدود یک و نیم تا دو سال پیش به یک عمل معنوی خاص و بسیار مجرب متشکل از «ناد علی» و سوره‌های خاصی از قرآن اشاره کرد. ماجرای رسیدن این عمل به او خود یک معجزه است. یک سید بزرگوار این عمل را به او عطا کرده بود و هنگام دادن آن حرف عجیبی زد: "امروز این عمل را از من بگیر؛ فردا آن را پیدا نخواهی کرد." مولانا این عمل و اجازه آن را در همان روز از او دریافت کرد. به کار روزگار نگاه کنید - درست روز بعد، آن سید بزرگوار درگذشت. گویی او به لحظات پایانی خود پی برده بود و می‌خواست این امانت معنوی را منتقل کند.</p>
      <p>مولانا دمشقی از نتایج شگفت‌انگیز و کرامات این عمل مبارک برایم گفت. من آن را یادداشت کردم، اما سپس در هیاهوی درگیری‌های دنیوی، از ذهنم پاک شد.</p>
      <p><strong>حادثه ناپدید شدن در مراسم چهلم:</strong><br>زمان گذشت. امسال، در ۴ آگوست ۲۰۲۶، به مناسبت چهلم شهدای کربلا، یک حادثه دلخراش رخ داد. یکی از مولاناهای آشنای ما به همراه پسرش در مراسم عزاداری گامه شاه در لاهور شرکت می‌کرد. پسر او تا حدودی دچار مشکل ذهنی بود. در میان جمعیت عظیم مراسم، کودک ناگهان در جایی ناپدید شد.</p>
      <p>تصور شرایطی که والدین باید در آن قرار داشته باشند دشوار است. هر تلاش ممکنی برای یافتن کودک انجام شد. اطلاعیه‌هایی در رسانه‌های اجتماعی منتشر شد، گزارش‌هایی در همه‌جا ثبت شد و برگه‌های اعلامیه در همه جا به اشتراک گذاشته شد، اما روزها گذشت و هیچ اثری از کودک نبود.</p>
      <p><strong>یک فکر الهام‌بخش و حمایت یک عمل معنوی:</strong><br>امروز ۲۴ آگوست است و ۲۰ روز کامل از این حادثه گذشته بود. چند روز پیش، مولانا یوسف حسین جوهری از سکردو پیامی در مورد این ناپدید شدن برای من فرستاد تا بتوانم آن را به دلیل وابستگی‌ام به رسانه‌ها به اشتراک بگذارم. ناگهان امروز، گویی فکری از جانب خداوند در قلبم قرار داده شد، آن عمل مشترک «ناد علی» و سوره‌های خاص قرآن را که مولانا کرامت علی دمشقی به من گفته بود به یاد آوردم.</p>
      <p>بلافاصله شماره پدر کودک گمشده را از مولانا یوسف جوهری گرفتم و از طرف دیگر، با مولانا دمشقی تماس گرفتم تا جزئیات آن عمل خاص را بپرسم. او از طریق یک پیام صوتی، روش کامل عمل را به من گفت، اجازه نحوه انجام این عمل ناد علی را همراه با سوره‌های خاصی از قرآن کریم صادر کرد و به من اطمینان داد که ان‌شاءالله ظرف ۱۰ روز، یا کودک خودش برمی‌گردد یا اثر قطعی از او پیدا می‌شود.</p>
      <p>بلافاصله با پدر کودک گمشده تماس گرفتم، به او دلداری دادم و آن عمل را به او منتقل کردم.</p>
      <p><strong>اللهم صل علی محمد و آل محمد. معجزه خاندان محمد (ع) و یک شگفتی عینی:</strong><br>هیچ چیز در درگاه خداوند غیرممکن نیست. به سختی دو یا سه ساعت از انتقال این عمل توسط من گذشته بود. و من حتی نمی‌دانم که آیا آن مولانا عمل سوره‌های قرآنی و ناد علی را شروع کرده بود یا به پایان رسانده بود، که ناگهان پیام او رسید: "کودک پیدا شد."</p>
      <p>به طور خودجوش، با شگفتی و شادی، با او تماس گرفتم و پرسیدم که چگونه این اتفاق افتاد. او به من گفت که کودک خودش به سلامت به خانه بازگشته است. کودکی که ۲۰ روز گم شده بود، که والدینش برای او در عذاب بودند، که با وجود جستجوی فراوان اثری از او یافت نمی‌شد، تنها در عرض چند ساعت از طریق برکت آن سوره‌های مبارک قرآنی و تلاوت ناد علی به سلامت به خانه رسید. این معجزه خاندان محمد (ع) است که من خود شاهد آن شده‌ام.</p>
      <p>اللهم صل علی محمد و آل محمد.<br>حتی قبل از این نیز، در زندگی خود، شگفتی مشابه و حیرت‌انگیزی از اثربخشی این تلاوت مبارک دیده بودم که برای خودم رخ داد.<br>جدای از این، یک پیر (راهنمای معنوی) آشنای من وجود دارد که فرصت شرکت در محفل معنوی او را داشتم. جمعیت زیادی از مردان و زنان در آن محفل حضور داشتند و من با چشمان خود دیدم که وقتی آن پیر «ناد علی» را روی بلندگو تلاوت می‌کند، به دلیل برکت و عظمت این تلاوت، جن‌های حاضر بر روی صدها نفر به طور همزمان ظاهر می‌شوند. این صحنه عینی از تأثیر ناد علی برای من چیزی کمتر از یک رویداد بسیار شگفت‌انگیز نبود.</p>
      <p><strong>پیام همدلی:</strong><br>این حادثه اعتقاد مرا بیش از پیش تقویت کرده است که حتی امروز نیز همان اثربخشی و معجزه در قرآن کریم و یاد اهل بیت (ع) وجود دارد. و ان‌شاءالله، همیشه باقی خواهد ماند. من این حادثه را نوشته‌ام تا به دست دوستان برسد و شاید برای کسی مفید باشد.</p>
      <p>خدای نکرده، اگر عزیز کسی گم شده باشد، یا هر مشکل اینچنینی وجود داشته باشد که به ظاهر راه حلی برای آن دیده نمی‌شود، می‌توانید برای این عمل خاص با من یا مولانا کرامت علی دمشقی تماس بگیرید. از آنجا که این عمل منوط به یک اجازه رسمی (اجازه) است که توسط یک سید بزرگوار به مولانا کرامت علی دمشقی اعطا شده است، و از لطف اوست که به من نیز اجازه انتقال این عمل به افراد مسئول را داده است، ما می‌توانیم آن را با اجازه برای رضای خدا و برای حل مشکلات بشریتِ در رنج به شما منتقل کنیم.</p>
      <p>خداوند متعال عزیزان همه را در امان نگه دارد و به خاطر گره‌گشای مشکلات (مشکل گشا)، مشکلات همه را آسان گرداند. آمین.</p>
    </div>`;

  // Apply full contents to arrays
  const enA1 = eData.find(a => a.id === '231-E'); if(enA1) enA1.content = art1EnContent;
  const enA2 = eData.find(a => a.id === '230-E'); if(enA2) enA2.content = art2EnContent;
  const enA3 = eData.find(a => a.id === '229-E'); if(enA3) enA3.content = art3EnContent;

  const faA1 = fData.find(a => a.id === '231-F'); if(faA1) faA1.content = art1FaContent;
  const faA2 = fData.find(a => a.id === '230-F'); if(faA2) faA2.content = art2FaContent;
  const faA3 = fData.find(a => a.id === '229-F'); if(faA3) faA3.content = art3FaContent;

  fs.writeFileSync(ePath, 'export const englishData = ' + JSON.stringify(eData, null, 2) + ';\n');
  fs.writeFileSync(fPath, 'export const farsiData = ' + JSON.stringify(fData, null, 2) + ';\n');
  
  console.log("Full translations applied!");
}

updateTranslations().catch(console.error);
